### ISSUE TITLE
can't build for python 3

### ISSUE THREAD

**Issue by antonymayi** [sony/v8eval#14]
how is it supposed to be built for python 3(.5) - the depot_tools look to be supported only on python 2?

```
  File "/tmp/v8eval/depot_tools/fetch.py", line 63
    print 'Running: %s' % (' '.join(pipes.quote(x) for x in cmd))
                      ^
SyntaxError: invalid syntax
/tmp/v8eval/build.sh: 55: cd: can't cd to v8
```

**Comment by antonymayi** [comment]
ok, managed to build it:
1. run just `v8eval/build.sh` under python2 environment
2. delete `v8eval/build/libv8eval_python.a` and `v8eval/build/CMakeFiles/v8eval_python.dir/src/v8eval_python.cxx.o`
3. switch to python3 environment
4. chdir to `v8eval/build` and run `make` to rebuild the python extensions for python3
5. edit `v8eval/setup.py` commenting out the line where it calls `system(v8eval_root + "/build.sh")` (we've just done that build manually)
6. run `v8eval/python/build.sh install`

**Comment by YoshiyukiMineo** [comment]
I have fixed this issue. Let me know if any issues.

**Comment by antonymayi** [comment]
yes, this works great now, thanks a lot!
