### ISSUE TITLE
can't install library on ubuntu 17.10

### ISSUE THREAD

**Issue by Olmer1st** [sony/v8eval#27]
**sudo -H pip install v8eval==0.2.7**
Collecting v8eval==0.2.7
  Downloading v8eval-0.2.7.tar.gz
Building wheels for collected packages: v8eval
  Running setup.py bdist_wheel for v8eval ... error
  Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-EhSBm0/v8eval/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmpqCKL2epip-wheel- --python-tag cp27:
  -- Configuring done
  -- Generating done
  -- Build files have been written to: /tmp/pip-build-EhSBm0/v8eval/build
  /usr/bin/cmake -H/tmp/pip-build-EhSBm0/v8eval -B/tmp/pip-build-EhSBm0/v8eval/build --check-build-system CMakeFiles/Makefile.cmake 0
  /usr/bin/cmake -E cmake_progress_start /tmp/pip-build-EhSBm0/v8eval/build/CMakeFiles /tmp/pip-build-EhSBm0/v8eval/build/CMakeFiles/progress.marks
  make -f CMakeFiles/Makefile2 all
  make[1]: Entering directory '/tmp/pip-build-EhSBm0/v8eval/build'
  make -f CMakeFiles/v8eval_ruby.dir/build.make CMakeFiles/v8eval_ruby.dir/depend
  make[2]: Entering directory '/tmp/pip-build-EhSBm0/v8eval/build'
  cd /tmp/pip-build-EhSBm0/v8eval/build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /tmp/pip-build-EhSBm0/v8eval /tmp/pip-build-EhSBm0/v8eval /tmp/pip-build-EhSBm0/v8eval/build /tmp/pip-build-EhSBm0/v8eval/build /tmp/pip-build-EhSBm0/v8eval/build/CMakeFiles/v8eval_ruby.dir/DependInfo.cmake --color=
  make[2]: Leaving directory '/tmp/pip-build-EhSBm0/v8eval/build'
  make -f CMakeFiles/v8eval_ruby.dir/build.make CMakeFiles/v8eval_ruby.dir/build
  make[2]: Entering directory '/tmp/pip-build-EhSBm0/v8eval/build'
  make[2]: Nothing to be done for 'CMakeFiles/v8eval_ruby.dir/build'.
  make[2]: Leaving directory '/tmp/pip-build-EhSBm0/v8eval/build'
  [ 22%] Built target v8eval_ruby
  make -f CMakeFiles/v8eval_python.dir/build.make CMakeFiles/v8eval_python.dir/depend
  make[2]: Entering directory '/tmp/pip-build-EhSBm0/v8eval/build'
  cd /tmp/pip-build-EhSBm0/v8eval/build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /tmp/pip-build-EhSBm0/v8eval /tmp/pip-build-EhSBm0/v8eval /tmp/pip-build-EhSBm0/v8eval/build /tmp/pip-build-EhSBm0/v8eval/build /tmp/pip-build-EhSBm0/v8eval/build/CMakeFiles/v8eval_python.dir/DependInfo.cmake --color=
  make[2]: Leaving directory '/tmp/pip-build-EhSBm0/v8eval/build'
  make -f CMakeFiles/v8eval_python.dir/build.make CMakeFiles/v8eval_python.dir/build
  make[2]: Entering directory '/tmp/pip-build-EhSBm0/v8eval/build'
  make[2]: Nothing to be done for 'CMakeFiles/v8eval_python.dir/build'.
  make[2]: Leaving directory '/tmp/pip-build-EhSBm0/v8eval/build'
  [ 44%] Built target v8eval_python
  make -f CMakeFiles/v8eval.dir/build.make CMakeFiles/v8eval.dir/depend
  make[2]: Entering directory '/tmp/pip-build-EhSBm0/v8eval/build'
  cd /tmp/pip-build-EhSBm0/v8eval/build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /tmp/pip-build-EhSBm0/v8eval /tmp/pip-build-EhSBm0/v8eval /tmp/pip-build-EhSBm0/v8eval/build /tmp/pip-build-EhSBm0/v8eval/build /tmp/pip-build-EhSBm0/v8eval/build/CMakeFiles/v8eval.dir/DependInfo.cmake --color=
  make[2]: Leaving directory '/tmp/pip-build-EhSBm0/v8eval/build'
  make -f CMakeFiles/v8eval.dir/build.make CMakeFiles/v8eval.dir/build
  make[2]: Entering directory '/tmp/pip-build-EhSBm0/v8eval/build'
  make[2]: Nothing to be done for 'CMakeFiles/v8eval.dir/build'.
  make[2]: Leaving directory '/tmp/pip-build-EhSBm0/v8eval/build'
  [ 77%] Built target v8eval
  make -f CMakeFiles/v8eval_go.dir/build.make CMakeFiles/v8eval_go.dir/depend
  make[2]: Entering directory '/tmp/pip-build-EhSBm0/v8eval/build'
  cd /tmp/pip-build-EhSBm0/v8eval/build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /tmp/pip-build-EhSBm0/v8eval /tmp/pip-build-EhSBm0/v8eval /tmp/pip-build-EhSBm0/v8eval/build /tmp/pip-build-EhSBm0/v8eval/build /tmp/pip-build-EhSBm0/v8eval/build/CMakeFiles/v8eval_go.dir/DependInfo.cmake --color=
  make[2]: Leaving directory '/tmp/pip-build-EhSBm0/v8eval/build'
  make -f CMakeFiles/v8eval_go.dir/build.make CMakeFiles/v8eval_go.dir/build
  make[2]: Entering directory '/tmp/pip-build-EhSBm0/v8eval/build'
  make[2]: Nothing to be done for 'CMakeFiles/v8eval_go.dir/build'.
  make[2]: Leaving directory '/tmp/pip-build-EhSBm0/v8eval/build'
  [100%] Built target v8eval_go
  make[1]: Leaving directory '/tmp/pip-build-EhSBm0/v8eval/build'
  /usr/bin/cmake -E cmake_progress_start /tmp/pip-build-EhSBm0/v8eval/build/CMakeFiles 0
  running bdist_wheel
  running build
  running build_py
  creating build/lib.linux-x86_64-2.7
  copying python/v8eval/v8eval.py -> build/lib.linux-x86_64-2.7
  running build_ext
  building '_v8eval' extension
  creating build/temp.linux-x86_64-2.7
  creating build/temp.linux-x86_64-2.7/tmp
  creating build/temp.linux-x86_64-2.7/tmp/pip-build-EhSBm0
  creating build/temp.linux-x86_64-2.7/tmp/pip-build-EhSBm0/v8eval
  creating build/temp.linux-x86_64-2.7/tmp/pip-build-EhSBm0/v8eval/python
  creating build/temp.linux-x86_64-2.7/tmp/pip-build-EhSBm0/v8eval/python/v8eval
  /tmp/pip-build-EhSBm0/v8eval/v8/third_party/llvm-build/Release+Asserts/bin/clang -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-l1RrwO/python2.7-2.7.14=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/tmp/pip-build-EhSBm0/v8eval/v8 -I/tmp/pip-build-EhSBm0/v8eval/v8/include -I/tmp/pip-build-EhSBm0/v8eval/uv/include -I/usr/include/python2.7 -c /tmp/pip-build-EhSBm0/v8eval/python/v8eval/v8eval_wrap.cxx -o build/temp.linux-x86_64-2.7/tmp/pip-build-EhSBm0/v8eval/python/v8eval/v8eval_wrap.o -O3 -std=c++11
  In file included from /tmp/pip-build-EhSBm0/v8eval/python/v8eval/v8eval_wrap.cxx:173:
  In file included from /usr/include/python2.7/Python.h:85:
  /usr/include/python2.7/unicodeobject.h:534:5: warning: 'register' storage class specifier is deprecated and incompatible with C++17 [-Wdeprecated-register]
      register PyObject *obj,     /* Object */
      ^~~~~~~~~
  /usr/include/python2.7/unicodeobject.h:553:5: warning: 'register' storage class specifier is deprecated and incompatible with C++17 [-Wdeprecated-register]
      register PyObject *obj      /* Object */
      ^~~~~~~~~
  /usr/include/python2.7/unicodeobject.h:575:5: warning: 'register' storage class specifier is deprecated and incompatible with C++17 [-Wdeprecated-register]
      register const wchar_t *w,  /* wchar_t buffer */
      ^~~~~~~~~
  /usr/include/python2.7/unicodeobject.h:593:5: warning: 'register' storage class specifier is deprecated and incompatible with C++17 [-Wdeprecated-register]
      register wchar_t *w,        /* wchar_t buffer */
      ^~~~~~~~~
  In file included from /tmp/pip-build-EhSBm0/v8eval/python/v8eval/v8eval_wrap.cxx:173:
  In file included from /usr/include/python2.7/Python.h:94:
  /usr/include/python2.7/stringobject.h:173:5: warning: 'register' storage class specifier is deprecated and incompatible with C++17 [-Wdeprecated-register]
      register PyObject *obj,     /* string or Unicode object */
      ^~~~~~~~~
  /usr/include/python2.7/stringobject.h:174:5: warning: 'register' storage class specifier is deprecated and incompatible with C++17 [-Wdeprecated-register]
      register char **s,          /* pointer to buffer variable */
      ^~~~~~~~~
  /usr/include/python2.7/stringobject.h:175:5: warning: 'register' storage class specifier is deprecated and incompatible with C++17 [-Wdeprecated-register]
      register Py_ssize_t *len    /* pointer to length variable or NULL
      ^~~~~~~~~
  7 warnings generated.
  /tmp/pip-build-EhSBm0/v8eval/v8/third_party/llvm-build/Release+Asserts/bin/clang++ -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-l1RrwO/python2.7-2.7.14=. -fstack-protector-strong -Wformat -Werror=format-security -Wl,-Bsymbolic-functions -Wl,-z,relro -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-l1RrwO/python2.7-2.7.14=. -fstack-protector-strong -Wformat -Werror=format-security build/temp.linux-x86_64-2.7/tmp/pip-build-EhSBm0/v8eval/python/v8eval/v8eval_wrap.o -L/tmp/pip-build-EhSBm0/v8eval/build -L/tmp/pip-build-EhSBm0/v8eval/uv/.libs -L/tmp/pip-build-EhSBm0/v8eval/v8/out/x64.release/obj.target/src -lv8eval -lv8eval_python -lv8_libplatform -lv8_base -lv8_libbase -lv8_libsampler -lv8_nosnapshot -luv -lrt -o build/lib.linux-x86_64-2.7/_v8eval.so
  /usr/bin/ld: cannot find -lv8_libplatform
  /usr/bin/ld: cannot find -lv8_base
  /usr/bin/ld: cannot find -lv8_libbase
  /usr/bin/ld: cannot find -lv8_libsampler
  /usr/bin/ld: cannot find -lv8_nosnapshot
  clang: error: linker command failed with exit code 1 (use -v to see invocation)
  error: command '/tmp/pip-build-EhSBm0/v8eval/v8/third_party/llvm-build/Release+Asserts/bin/clang++' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for v8eval
  Running setup.py clean for v8eval
Failed to build v8eval
Installing collected packages: v8eval
  Running setup.py install for v8eval ... error
    Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-EhSBm0/v8eval/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-4qaNKS-record/install-record.txt --single-version-externally-managed --compile:
    -- Configuring done
    -- Generating done
    -- Build files have been written to: /tmp/pip-build-EhSBm0/v8eval/build
    /usr/bin/cmake -H/tmp/pip-build-EhSBm0/v8eval -B/tmp/pip-build-EhSBm0/v8eval/build --check-build-system CMakeFiles/Makefile.cmake 0
    /usr/bin/cmake -E cmake_progress_start /tmp/pip-build-EhSBm0/v8eval/build/CMakeFiles /tmp/pip-build-EhSBm0/v8eval/build/CMakeFiles/progress.marks
    make -f CMakeFiles/Makefile2 all
    make[1]: Entering directory '/tmp/pip-build-EhSBm0/v8eval/build'
    make -f CMakeFiles/v8eval_ruby.dir/build.make CMakeFiles/v8eval_ruby.dir/depend
    make[2]: Entering directory '/tmp/pip-build-EhSBm0/v8eval/build'
    cd /tmp/pip-build-EhSBm0/v8eval/build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /tmp/pip-build-EhSBm0/v8eval /tmp/pip-build-EhSBm0/v8eval /tmp/pip-build-EhSBm0/v8eval/build /tmp/pip-build-EhSBm0/v8eval/build /tmp/pip-build-EhSBm0/v8eval/build/CMakeFiles/v8eval_ruby.dir/DependInfo.cmake --color=
    make[2]: Leaving directory '/tmp/pip-build-EhSBm0/v8eval/build'
    make -f CMakeFiles/v8eval_ruby.dir/build.make CMakeFiles/v8eval_ruby.dir/build
    make[2]: Entering directory '/tmp/pip-build-EhSBm0/v8eval/build'
    make[2]: Nothing to be done for 'CMakeFiles/v8eval_ruby.dir/build'.
    make[2]: Leaving directory '/tmp/pip-build-EhSBm0/v8eval/build'
    [ 22%] Built target v8eval_ruby
    make -f CMakeFiles/v8eval_python.dir/build.make CMakeFiles/v8eval_python.dir/depend
    make[2]: Entering directory '/tmp/pip-build-EhSBm0/v8eval/build'
    cd /tmp/pip-build-EhSBm0/v8eval/build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /tmp/pip-build-EhSBm0/v8eval /tmp/pip-build-EhSBm0/v8eval /tmp/pip-build-EhSBm0/v8eval/build /tmp/pip-build-EhSBm0/v8eval/build /tmp/pip-build-EhSBm0/v8eval/build/CMakeFiles/v8eval_python.dir/DependInfo.cmake --color=
    make[2]: Leaving directory '/tmp/pip-build-EhSBm0/v8eval/build'
    make -f CMakeFiles/v8eval_python.dir/build.make CMakeFiles/v8eval_python.dir/build
    make[2]: Entering directory '/tmp/pip-build-EhSBm0/v8eval/build'
    make[2]: Nothing to be done for 'CMakeFiles/v8eval_python.dir/build'.
    make[2]: Leaving directory '/tmp/pip-build-EhSBm0/v8eval/build'
    [ 44%] Built target v8eval_python
    make -f CMakeFiles/v8eval.dir/build.make CMakeFiles/v8eval.dir/depend
    make[2]: Entering directory '/tmp/pip-build-EhSBm0/v8eval/build'
    cd /tmp/pip-build-EhSBm0/v8eval/build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /tmp/pip-build-EhSBm0/v8eval /tmp/pip-build-EhSBm0/v8eval /tmp/pip-build-EhSBm0/v8eval/build /tmp/pip-build-EhSBm0/v8eval/build /tmp/pip-build-EhSBm0/v8eval/build/CMakeFiles/v8eval.dir/DependInfo.cmake --color=
    make[2]: Leaving directory '/tmp/pip-build-EhSBm0/v8eval/build'
    make -f CMakeFiles/v8eval.dir/build.make CMakeFiles/v8eval.dir/build
    make[2]: Entering directory '/tmp/pip-build-EhSBm0/v8eval/build'
    make[2]: Nothing to be done for 'CMakeFiles/v8eval.dir/build'.
    make[2]: Leaving directory '/tmp/pip-build-EhSBm0/v8eval/build'
    [ 77%] Built target v8eval
    make -f CMakeFiles/v8eval_go.dir/build.make CMakeFiles/v8eval_go.dir/depend
    make[2]: Entering directory '/tmp/pip-build-EhSBm0/v8eval/build'
    cd /tmp/pip-build-EhSBm0/v8eval/build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /tmp/pip-build-EhSBm0/v8eval /tmp/pip-build-EhSBm0/v8eval /tmp/pip-build-EhSBm0/v8eval/build /tmp/pip-build-EhSBm0/v8eval/build /tmp/pip-build-EhSBm0/v8eval/build/CMakeFiles/v8eval_go.dir/DependInfo.cmake --color=
    make[2]: Leaving directory '/tmp/pip-build-EhSBm0/v8eval/build'
    make -f CMakeFiles/v8eval_go.dir/build.make CMakeFiles/v8eval_go.dir/build
    make[2]: Entering directory '/tmp/pip-build-EhSBm0/v8eval/build'
    make[2]: Nothing to be done for 'CMakeFiles/v8eval_go.dir/build'.
    make[2]: Leaving directory '/tmp/pip-build-EhSBm0/v8eval/build'
    [100%] Built target v8eval_go
    make[1]: Leaving directory '/tmp/pip-build-EhSBm0/v8eval/build'
    /usr/bin/cmake -E cmake_progress_start /tmp/pip-build-EhSBm0/v8eval/build/CMakeFiles 0
    running install
    running build
    running build_py
    creating build/lib.linux-x86_64-2.7
    copying python/v8eval/v8eval.py -> build/lib.linux-x86_64-2.7
    running build_ext
    building '_v8eval' extension
    creating build/temp.linux-x86_64-2.7
    creating build/temp.linux-x86_64-2.7/tmp
    creating build/temp.linux-x86_64-2.7/tmp/pip-build-EhSBm0
    creating build/temp.linux-x86_64-2.7/tmp/pip-build-EhSBm0/v8eval
    creating build/temp.linux-x86_64-2.7/tmp/pip-build-EhSBm0/v8eval/python
    creating build/temp.linux-x86_64-2.7/tmp/pip-build-EhSBm0/v8eval/python/v8eval
    /tmp/pip-build-EhSBm0/v8eval/v8/third_party/llvm-build/Release+Asserts/bin/clang -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-l1RrwO/python2.7-2.7.14=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/tmp/pip-build-EhSBm0/v8eval/v8 -I/tmp/pip-build-EhSBm0/v8eval/v8/include -I/tmp/pip-build-EhSBm0/v8eval/uv/include -I/usr/include/python2.7 -c /tmp/pip-build-EhSBm0/v8eval/python/v8eval/v8eval_wrap.cxx -o build/temp.linux-x86_64-2.7/tmp/pip-build-EhSBm0/v8eval/python/v8eval/v8eval_wrap.o -O3 -std=c++11
    In file included from /tmp/pip-build-EhSBm0/v8eval/python/v8eval/v8eval_wrap.cxx:173:
    In file included from /usr/include/python2.7/Python.h:85:
    /usr/include/python2.7/unicodeobject.h:534:5: warning: 'register' storage class specifier is deprecated and incompatible with C++17 [-Wdeprecated-register]
        register PyObject *obj,     /* Object */
        ^~~~~~~~~
    /usr/include/python2.7/unicodeobject.h:553:5: warning: 'register' storage class specifier is deprecated and incompatible with C++17 [-Wdeprecated-register]
        register PyObject *obj      /* Object */
        ^~~~~~~~~
    /usr/include/python2.7/unicodeobject.h:575:5: warning: 'register' storage class specifier is deprecated and incompatible with C++17 [-Wdeprecated-register]
        register const wchar_t *w,  /* wchar_t buffer */
        ^~~~~~~~~
    /usr/include/python2.7/unicodeobject.h:593:5: warning: 'register' storage class specifier is deprecated and incompatible with C++17 [-Wdeprecated-register]
        register wchar_t *w,        /* wchar_t buffer */
        ^~~~~~~~~
    In file included from /tmp/pip-build-EhSBm0/v8eval/python/v8eval/v8eval_wrap.cxx:173:
    In file included from /usr/include/python2.7/Python.h:94:
    /usr/include/python2.7/stringobject.h:173:5: warning: 'register' storage class specifier is deprecated and incompatible with C++17 [-Wdeprecated-register]
        register PyObject *obj,     /* string or Unicode object */
        ^~~~~~~~~
    /usr/include/python2.7/stringobject.h:174:5: warning: 'register' storage class specifier is deprecated and incompatible with C++17 [-Wdeprecated-register]
        register char **s,          /* pointer to buffer variable */
        ^~~~~~~~~
    /usr/include/python2.7/stringobject.h:175:5: warning: 'register' storage class specifier is deprecated and incompatible with C++17 [-Wdeprecated-register]
        register Py_ssize_t *len    /* pointer to length variable or NULL
        ^~~~~~~~~
    7 warnings generated.
    /tmp/pip-build-EhSBm0/v8eval/v8/third_party/llvm-build/Release+Asserts/bin/clang++ -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-l1RrwO/python2.7-2.7.14=. -fstack-protector-strong -Wformat -Werror=format-security -Wl,-Bsymbolic-functions -Wl,-z,relro -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-l1RrwO/python2.7-2.7.14=. -fstack-protector-strong -Wformat -Werror=format-security build/temp.linux-x86_64-2.7/tmp/pip-build-EhSBm0/v8eval/python/v8eval/v8eval_wrap.o -L/tmp/pip-build-EhSBm0/v8eval/build -L/tmp/pip-build-EhSBm0/v8eval/uv/.libs -L/tmp/pip-build-EhSBm0/v8eval/v8/out/x64.release/obj.target/src -lv8eval -lv8eval_python -lv8_libplatform -lv8_base -lv8_libbase -lv8_libsampler -lv8_nosnapshot -luv -lrt -o build/lib.linux-x86_64-2.7/_v8eval.so
    /usr/bin/ld: cannot find -lv8_libplatform
    /usr/bin/ld: cannot find -lv8_base
    /usr/bin/ld: cannot find -lv8_libbase
    /usr/bin/ld: cannot find -lv8_libsampler
    /usr/bin/ld: cannot find -lv8_nosnapshot
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    error: command '/tmp/pip-build-EhSBm0/v8eval/v8/third_party/llvm-build/Release+Asserts/bin/clang++' failed with exit status 1
    
    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-EhSBm0/v8eval/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-4qaNKS-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-EhSBm0/v8eval/

**Comment by Olmer1st** [comment]
git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
Cloning into 'depot_tools'...
remote: Sending approximately 17.44 MiB ...
remote: Total 25020 (delta 18265), reused 25020 (delta 18265)
Receiving objects: 100% (25020/25020), 17.44 MiB | 845.00 KiB/s, done.
Resolving deltas: 100% (18265/18265), done.
vadim@vadim-laptop:~/projects$ export PATH=`pwd`/depot_tools:"$PATH"
vadim@vadim-laptop:~/projects$ fetch v8
Running: gclient root
Running: gclient config --spec 'solutions = [
  {
    "url": "https://chromium.googlesource.com/v8/v8.git",
    "managed": False,
    "name": "v8",
    "deps_file": "DEPS",
    "custom_deps": {},
  },
]
'
Running: gclient sync --with_branch_heads
Error: Command 'download_from_google_storage --no_resume --platform=linux* --no_auth --bucket chromium-clang-format -s v8/buildtools/linux64/clang-format.sha1' returned non-zero exit status 1 in /home/vadim/projects
Traceback (most recent call last):
  File "/home/vadim/projects/depot_tools/fetch.py", line 301, in <module>
    sys.exit(main())
  File "/home/vadim/projects/depot_tools/fetch.py", line 296, in main
    return run(options, spec, root)
  File "/home/vadim/projects/depot_tools/fetch.py", line 290, in run
    return checkout.init()
  File "/home/vadim/projects/depot_tools/fetch.py", line 133, in init
    self.run_gclient(*sync_cmd)
  File "/home/vadim/projects/depot_tools/fetch.py", line 78, in run_gclient
    return self.run(cmd_prefix + cmd, **kwargs)
  File "/home/vadim/projects/depot_tools/fetch.py", line 68, in run
    return subprocess.check_output(cmd, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 219, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '('gclient', 'sync', '--with_branch_heads')' returned non-zero exit status 2

**Comment by YoshiyukiMineo** [comment]
I have fixed build errors and released new version. Could you try again?

**Comment by Olmer1st** [comment]
Great! Thank you! Installed successfully. sudo -H pip install v8eval
